global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.16.100.145:9100']

  - job_name: 'snipeit'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.16.100.142:9100']

# BlackBox

  - job_name: 'blackbox-HTTP'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://172.16.100.145
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.16.100.145:9115

  - job_name: 'Blackbox-ICMP'
    scrape_interval: 5m
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 172.16.100.145
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.16.100.145:9115
